CREATE TABLE cursos (
	id SERIAL PRIMARY KEY NOT NULL,
	nome VARCHAR(100),
	descricao TEXT,
	ativo BOOLEAN DEFAULT TRUE NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	atualizado_em TIMESTAMP
);

CREATE TABLE alunos (
	id SERIAL PRIMARY KEY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	matricula INT NOT NULL UNIQUE,
	senha VARCHAR(50) NOT NULL,
	idCurso INTEGER REFERENCES cursos(id),
	ativo BOOLEAN DEFAULT TRUE NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	atualizado_em TIMESTAMP
);

CREATE TABLE professores (
	id SERIAL PRIMARY KEY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	matricula INT NOT NULL UNIQUE,
	senha VARCHAR(50),
	ativo BOOLEAN DEFAULT TRUE NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	atualizado_em TIMESTAMP
);

CREATE TABLE disciplinas(
	id SERIAL PRIMARY KEY NOT NULL,
	codigo VARCHAR(50) UNIQUE NOT NULL,
	nome VARCHAR(50),
	idCurso INTEGER REFERENCES cursos(id),
	idProf INTEGER REFERENCES professor(id),
	ativo BOOLEAN DEFAULT TRUE NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	atualizado_em TIMESTAMP
);
	   
CREATE TABLE aluno_disciplina_professor (
	id SERIAL PRIMARY KEY NOT NULL,
	av1 FLOAT,
	av2 FLOAT,
	media FLOAT,
	id_aluno INTEGER REFERENCES alunos(id),
	id_disciplina INTEGER REFERENCES disciplinas(id),
	id_professor INTEGER REFERENCES professores(id),
	ativo BOOLEAN DEFAULT TRUE NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	atualizado_em TIMESTAMP
);